server:
  port: 8111

spring:
  application:
    name: swcamp-user-service

  ## db config
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/menudb
    username: root
    password: 1234

  ## jpa config
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    datasource: mysql
    properties:
      hibernate:
        '[format_sql]': true

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

hello:
  message: Welcomte to 9th SW-Camp
